@startuml

package App-Scene [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/App.tscn]] {
    class App  {
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/App.cs ScriptFile]]
        [Provisions]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/App.cs:32 IAppRepo]] - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/domain/AppRepo.cs Script]]
        --
        [Nodes]
        Menu - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menu/Menu.cs Script]]
        Splash - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menu/splash/Splash.cs Script]]
        [Properties]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/App.cs:51 AnimationPlayer]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/App.cs:41 AppBinding]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/App.cs:39 AppLogic]] - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/state/AppLogic.cs Script]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/App.cs:38 AppRepo]] - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/domain/AppRepo.cs Script]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/App.cs:50 BlankScreen]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/App.cs:25 Game]] - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/Game.cs Script]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/App.cs:49 GamePreview]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/App.cs:26 Instantiator]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/App.cs:47 Menu]] - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menu/Menu.cs Script]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/App.cs:48 SettingsMenu]] - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs Script]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/App.cs:52 Splash]] - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menu/splash/Splash.cs Script]]
        --
        [Methods]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/App.cs:15 _Notification()]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/App.cs:176 FadeInFromBlack()]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/App.cs:182 FadeToBlack()]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/App.cs:188 HideMenus()]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/App.cs:56 Initialize()]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/App.cs:160 OnAnimationFinished()]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/App.cs:214 OnAppliedDisplaySettings()]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/App.cs:194 OnExitTree()]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/App.cs:154 OnLoadGame()]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/App.cs:158 OnMainMenu()]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/App.cs:152 OnNewGame()]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/App.cs:78 OnReady()]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/App.cs:208 OnSaveFileLoaded()]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/App.cs:156 OnSettings()]]
    }
    class Menu  {
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menu/Menu.cs ScriptFile]]
        [Interface Properties]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menu/Menu.cs:22 NewGameButton]]
        [Properties]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menu/Menu.cs:24 LoadGameButton]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menu/Menu.cs:27 SettingsButton]]
        --
        [Methods]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menu/Menu.cs:19 _Notification()]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menu/Menu.cs:47 OnExitTree()]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menu/Menu.cs:55 OnLoadGamePressed()]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menu/Menu.cs:54 OnNewGamePressed()]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menu/Menu.cs:40 OnReady()]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menu/Menu.cs:56 OnSettingsPressed()]]
    }
    class Splash  {
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menu/splash/Splash.cs ScriptFile]]
        [Dependencies]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menu/splash/Splash.cs:21 AppRepo]] - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/domain/AppRepo.cs Script]]
        --
        [Properties]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menu/splash/Splash.cs:16 AnimationPlayer]]
        --
        [Methods]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menu/splash/Splash.cs:34 _Input()]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menu/splash/Splash.cs:13 _Notification()]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menu/splash/Splash.cs:31 OnAnimationFinished()]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menu/splash/Splash.cs:28 OnExitTree()]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menu/splash/Splash.cs:25 OnReady()]]
    }
    class AppLogic  {
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/state/AppLogic.cs ScriptFile]]
        [Methods]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/state/AppLogic.cs:12 GetInitialState()]]
    }
    class AppRepo  {
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/domain/AppRepo.cs ScriptFile]]
        [Properties]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/domain/AppRepo.cs:84 FileSystem]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/domain/AppRepo.cs:81 JsonOptions]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/domain/AppRepo.cs:85 SettingsFilePath]]
        --
        [Interface Methods]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/domain/AppRepo.cs:216 ApplyDisplaySettings()]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/domain/AppRepo.cs:107 GetSavedDisplaySettings()]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/domain/AppRepo.cs:103 OnEnterGame()]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/domain/AppRepo.cs:104 OnExitGame()]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/domain/AppRepo.cs:101 OnMainMenuEntered()]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/domain/AppRepo.cs:105 OnSettingsMenuEntered()]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/domain/AppRepo.cs:182 SaveDisplaySettings()]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/domain/AppRepo.cs:99 SkipSplashScreen()]]
        [Methods]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/domain/AppRepo.cs:224 Dispose()]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/domain/AppRepo.cs:241 Dispose()]]
    }
    package Game-Scene [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/Game.tscn]] {
        class Game  {
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/Game.cs ScriptFile]]
            [Dependencies]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/Game.cs:74 AppRepo]] - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/domain/AppRepo.cs Script]]
            [Provisions]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/Game.cs:68 IGameRepo]] - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/domain/GameRepo.cs Script]]
            --
            [Nodes]
            PlayerCamera - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player_camera/PlayerCamera.cs Script]]
            Player - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/Player.cs Script]]
            Map - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/map/Map.cs Script]]
            InGameUi - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/in_game_ui/InGameUI.cs Script]]
            InGameAudio - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/in_game_audio/InGameAudio.cs Script]]
            DeathMenu - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/death_menu/DeathMenu.cs Script]]
            WinMenu - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/win_menu/WinMenu.cs Script]]
            PauseMenu - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/pause_menu/PauseMenu.cs Script]]
            [Properties]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/Game.cs:60 DeathMenu]] - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/death_menu/DeathMenu.cs Script]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/Game.cs:36 EntityTable]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/Game.cs:34 Environment]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/Game.cs:33 FileSystem]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/Game.cs:48 GameBinding]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/Game.cs:39 GameChunk]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/Game.cs:46 GameLogic]] - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/state/GameLogic.cs Script]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/Game.cs:45 GameRepo]] - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/domain/GameRepo.cs Script]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/Game.cs:59 InGameUi]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/Game.cs:31 JsonOptions]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/Game.cs:58 Map]] - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/map/Map.cs Script]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/Game.cs:62 PauseMenu]] - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/pause_menu/PauseMenu.cs Script]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/Game.cs:56 Player]] - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/Player.cs Script]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/Game.cs:54 PlayerCamera]] - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player_camera/PlayerCamera.cs Script]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/Game.cs:38 SaveFile]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/Game.cs:35 SaveFilePath]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/Game.cs:61 WinMenu]] - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/win_menu/WinMenu.cs Script]]
            --
            [Interface Methods]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/Game.cs:279 LoadExistingGame()]]
            [Methods]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/Game.cs:235 _Input()]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/Game.cs:26 _Notification()]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/Game.cs:285 FinishedLoadingSaveFile()]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/Game.cs:261 OnDeathMenuTransitioned()]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/Game.cs:264 OnExitTree()]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/Game.cs:243 OnMainMenu()]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/Game.cs:258 OnPauseMenuSaveRequested()]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/Game.cs:255 OnPauseMenuTransitioned()]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/Game.cs:147 OnResolved()]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/Game.cs:246 OnResume()]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/Game.cs:249 OnStart()]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/Game.cs:252 OnWinMenuTransitioned()]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/Game.cs:288 SetPauseMode()]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/Game.cs:78 Setup()]]
        }
        package PlayerCamera-Scene [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player_camera/PlayerCamera.tscn]] {
            class PlayerCamera  {
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player_camera/PlayerCamera.cs ScriptFile]]
                [Dependencies]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player_camera/PlayerCamera.cs:72 GameRepo]] - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/domain/GameRepo.cs Script]]
                --
                [Interface Properties]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player_camera/PlayerCamera.cs:113 CameraBasis]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player_camera/PlayerCamera.cs:109 CameraLocalPosition]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player_camera/PlayerCamera.cs:74 CameraLogic]] - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player_camera/State/PlayerCameraLogic.cs Script]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player_camera/PlayerCamera.cs:110 GimbalRotationHorizontal]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player_camera/PlayerCamera.cs:111 GimbalRotationVertical]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player_camera/PlayerCamera.cs:82 Offset]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player_camera/PlayerCamera.cs:116 OffsetPosition]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player_camera/PlayerCamera.cs:108 SpringArmTargetPosition]]
                [Properties]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player_camera/PlayerCamera.cs:76 CameraBinding]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player_camera/PlayerCamera.cs:99 CameraNode]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player_camera/PlayerCamera.cs:93 GimbalHorizontalNode]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player_camera/PlayerCamera.cs:96 GimbalVerticalNode]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player_camera/PlayerCamera.cs:91 OffsetNode]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player_camera/PlayerCamera.cs:68 PlayerCameraChunk]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player_camera/PlayerCamera.cs:84 Settings]] - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player_camera/PlayerCameraSettings.cs Script]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player_camera/PlayerCamera.cs:101 SpringArmTarget]]
                --
                [Interface Methods]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player_camera/PlayerCamera.cs:218 UsePlayerCamera()]]
                [Methods]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player_camera/PlayerCamera.cs:210 _Input()]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player_camera/PlayerCamera.cs:62 _Notification()]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player_camera/PlayerCamera.cs:220 OnExitTree()]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player_camera/PlayerCamera.cs:185 OnPhysicsProcess()]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player_camera/PlayerCamera.cs:160 OnResolved()]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player_camera/PlayerCamera.cs:120 Setup()]]
            }
            class PlayerCameraLogic  {
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player_camera/State/PlayerCameraLogic.cs ScriptFile]]
                [Methods]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player_camera/State/PlayerCameraLogic.cs:19 GetInitialState()]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player_camera/State/PlayerCameraLogic.cs:21 OnStart()]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player_camera/State/PlayerCameraLogic.cs:40 OnStop()]]
            }
            class PlayerCameraSettings  {
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player_camera/PlayerCameraSettings.cs ScriptFile]]
                [Properties]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player_camera/PlayerCameraSettings.cs:11 JoypadSensitivity]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player_camera/PlayerCameraSettings.cs:8 MouseSensitivity]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player_camera/PlayerCameraSettings.cs:17 VerticalMax]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player_camera/PlayerCameraSettings.cs:23 VerticalMin]]
            }
            PlayerCamera::PlayerCameraLogic ---> PlayerCameraLogic
            PlayerCamera::PlayerCameraSettings ---> PlayerCameraSettings
        }
        package Player-Scene [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/Player.tscn]] {
            class Player  {
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/Player.cs ScriptFile]]
                [Dependencies]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/Player.cs:65 GameRepo]] - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/domain/GameRepo.cs Script]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/Player.cs:68 AppRepo]] - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/domain/AppRepo.cs Script]]
                [Provisions]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/Player.cs:59 IPlayerLogic]] - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/state/PlayerLogic.cs Script]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/Player.cs:60 PlayerLogic.Settings]] - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/state/PlayerLogic.Settings.cs Script]]
                --
                [Interface Properties]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/Player.cs:110 PlayerLogic]] - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/state/PlayerLogic.cs Script]]
                [Nodes]
                PlayerModel - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/PlayerModel.tscn Script]]
                [Properties]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/Player.cs:92 Acceleration]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/Player.cs:265 CenterOfMass]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/Player.cs:84 Gravity]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/Player.cs:103 JumpForce]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/Player.cs:96 JumpImpulseForce]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/Player.cs:88 MoveSpeed]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/Player.cs:113 PlayerBinding]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/Player.cs:54 PlayerChunk]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/Player.cs:76 RotationSpeed]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/Player.cs:111 Settings]] - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/state/PlayerLogic.Settings.cs Script]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/Player.cs:80 StoppingSpeed]]
                --
                [Interface Methods]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/Player.cs:213 GetGlobalInputVector()]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/Player.cs:229 GetNextRotationBasis()]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/Player.cs:250 IsMovingHorizontally()]]
                [Methods]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/Player.cs:46 _Notification()]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/Player.cs:271 Kill()]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/Player.cs:156 OnExitTree()]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/Player.cs:189 OnPhysicsProcess()]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/Player.cs:154 OnReady()]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/Player.cs:163 OnResolved()]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/Player.cs:258 Push()]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/Player.cs:117 Setup()]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/Player.cs:208 ShouldJump()]]
            }
            class PlayerLogic  {
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/state/PlayerLogic.cs ScriptFile]]
                [Methods]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/state/PlayerLogic.cs:12 GetInitialState()]]
            }
            class PlayerModel  {
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/ ScriptFile]]
                [Dependencies]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/PlayerModel.tscn:22 PlayerLogic]] - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/state/PlayerLogic.cs Script]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/PlayerModel.tscn:24 Settings]] - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/state/PlayerLogic.Settings.cs Script]]
                --
                [Properties]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/PlayerModel.tscn:34 AnimationStateMachine]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/PlayerModel.tscn:32 AnimationTree]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/PlayerModel.tscn:42 BlinkTimer]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/PlayerModel.tscn:40 CenterRoot]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/PlayerModel.tscn:28 PlayerBinding]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/PlayerModel.tscn:38 VisualRoot]]
                --
                [Methods]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/PlayerModel.tscn:13 _Notification()]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/PlayerModel.tscn:113 GetTarget()]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/PlayerModel.tscn:123 OnBlink()]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/PlayerModel.tscn:48 OnEnterTree()]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/PlayerModel.tscn:50 OnExitTree()]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/PlayerModel.tscn:56 OnReady()]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/player/PlayerModel.tscn:66 OnResolved()]]
            }
            Player::PlayerLogic ---> PlayerLogic
            Player::PlayerModel ---> PlayerModel
        }
        package Map-Scene [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/map/Map.tscn]] {
            class Map  {
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/map/Map.cs ScriptFile]]
                [Dependencies]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/map/Map.cs:43 GameRepo]] - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/domain/GameRepo.cs Script]]
                --
                [Nodes]
                DeathPlane - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/death_plane/DeathPlane.cs Script]]
                TreeTrunkSmall2 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/map/tree_trunk/TreeTrunkSmall.tscn Script]]
                TreeTrunkSmall - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/map/tree_trunk/TreeTrunkSmall.tscn Script]]
                LargeTreeTrunk - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/map/large_tree_trunk/LargeTreeTrunk.tscn Script]]
                Jumpshroom2 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/jumpshroom/Jumpshroom.cs Script]]
                Jumpshroom4 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/jumpshroom/Jumpshroom.cs Script]]
                Jumpshroom3 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/jumpshroom/Jumpshroom.cs Script]]
                Jumpshroom5 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/jumpshroom/Jumpshroom.cs Script]]
                Jumpshroom9 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/jumpshroom/Jumpshroom.cs Script]]
                Jumpshroom6 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/jumpshroom/Jumpshroom.cs Script]]
                Jumpshroom8 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/jumpshroom/Jumpshroom.cs Script]]
                Jumpshroom7 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/jumpshroom/Jumpshroom.cs Script]]
                Coin - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs Script]]
                Coin26 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs Script]]
                Coin27 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs Script]]
                Coin28 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs Script]]
                Coin29 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs Script]]
                Coin30 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs Script]]
                Coin43 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs Script]]
                Coin44 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs Script]]
                Coin31 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs Script]]
                Coin2 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs Script]]
                Coin32 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs Script]]
                Coin42 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs Script]]
                Coin33 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs Script]]
                Coin19 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs Script]]
                Coin24 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs Script]]
                Coin25 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs Script]]
                Coin20 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs Script]]
                Coin22 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs Script]]
                Coin3 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs Script]]
                Coin4 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs Script]]
                Coin9 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs Script]]
                Coin12 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs Script]]
                Coin15 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs Script]]
                Coin16 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs Script]]
                Coin13 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs Script]]
                Coin14 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs Script]]
                Coin38 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs Script]]
                Coin39 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs Script]]
                Coin41 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs Script]]
                Coin37 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs Script]]
                Coin5 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs Script]]
                Coin6 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs Script]]
                Coin7 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs Script]]
                Coin8 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs Script]]
                Coin10 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs Script]]
                Coin40 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs Script]]
                Coin17 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs Script]]
                Coin11 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs Script]]
                Coin34 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs Script]]
                Coin36 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs Script]]
                TreeTrunkSmall - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/map/tree_trunk/TreeTrunkSmall.tscn Script]]
                Jumpshroom - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/jumpshroom/Jumpshroom.cs Script]]
                Fence - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence2 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence3 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence4 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence8 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence12 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence13 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence9 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence10 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence11 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence14 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence15 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence16 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence17 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence5 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence6 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/map/fence/Fence.tscn Script]]
                Fence7 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/map/fence/Fence.tscn Script]]
                Cloud - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/map/cloud/Cloud.tscn Script]]
                Cloud2 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/map/cloud/Cloud.tscn Script]]
                Cloud3 - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/map/cloud/Cloud.tscn Script]]
                [Properties]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/map/Map.cs:37 Coins]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/map/Map.cs:30 MapChunk]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/map/Map.cs:44 MapLogic]] - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/map/state/MapLogic.cs Script]]
                --
                [Interface Methods]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/map/Map.cs:48 GetCoinCount()]]
                [Methods]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/map/Map.cs:21 _Notification()]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/map/Map.cs:52 OnResolved()]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/map/Map.cs:50 Setup()]]
            }
            class DeathPlane  {
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/death_plane/DeathPlane.cs ScriptFile]]
                [Methods]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/death_plane/DeathPlane.cs:10 _Notification()]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/death_plane/DeathPlane.cs:16 OnBodyEntered()]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/death_plane/DeathPlane.cs:14 OnExitTree()]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/death_plane/DeathPlane.cs:12 OnReady()]]
            }
            package Jumpshroom-Scene [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/jumpshroom/Jumpshroom.tscn]] {
                class Jumpshroom  {
                    [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/jumpshroom/Jumpshroom.cs ScriptFile]]
                    [Dependencies]
                    [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/jumpshroom/Jumpshroom.cs:50 GameRepo]] - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/domain/GameRepo.cs Script]]
                    --
                    [Properties]
                    [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/jumpshroom/Jumpshroom.cs:42 AnimationPlayer]]
                    [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/jumpshroom/Jumpshroom.cs:43 Area3D]]
                    [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/jumpshroom/Jumpshroom.cs:44 CooldownTimer]]
                    [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/jumpshroom/Jumpshroom.cs:35 ImpulseStrength]]
                    [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/jumpshroom/Jumpshroom.cs:32 JumpshroomBinding]]
                    [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/jumpshroom/Jumpshroom.cs:30 JumpshroomLogic]] - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/jumpshroom/state/JumpshroomLogic.cs Script]]
                    --
                    [Methods]
                    [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/jumpshroom/Jumpshroom.cs:19 _Notification()]]
                    [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/jumpshroom/Jumpshroom.cs:102 OnAnimationFinished()]]
                    [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/jumpshroom/Jumpshroom.cs:84 OnAreaBodyEntered()]]
                    [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/jumpshroom/Jumpshroom.cs:82 OnCooldownTimeout()]]
                    [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/jumpshroom/Jumpshroom.cs:105 OnExitTree()]]
                    [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/jumpshroom/Jumpshroom.cs:60 OnResolved()]]
                    [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/jumpshroom/Jumpshroom.cs:94 OnShroomLoaded()]]
                    [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/jumpshroom/Jumpshroom.cs:54 Setup()]]
                }
                class JumpshroomLogic  {
                    [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/jumpshroom/state/JumpshroomLogic.cs ScriptFile]]
                    [Methods]
                    [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/jumpshroom/state/JumpshroomLogic.cs:12 GetInitialState()]]
                }
                Jumpshroom::JumpshroomLogic ---> JumpshroomLogic
            }
            package Coin-Scene [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.tscn]] {
                class Coin  {
                    [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs ScriptFile]]
                    [Dependencies]
                    [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs:34 GameRepo]] - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/domain/GameRepo.cs Script]]
                    --
                    [Interface Properties]
                    [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs:36 CoinLogic]] - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/state/CoinLogic.cs Script]]
                    [Properties]
                    [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs:21 AnimationPlayer]]
                    [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs:39 CoinBinding]]
                    [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs:22 CoinModel]]
                    [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs:28 CollectionTimeInSeconds]]
                    [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs:45 CollectorDetector]]
                    [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs:37 Settings]]
                    --
                    [Methods]
                    [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs:17 _Notification()]]
                    [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs:110 OnCollectorDetectorBodyEntered()]]
                    [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs:120 OnExitTree()]]
                    [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs:107 OnPhysicsProcess()]]
                    [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs:62 OnReady()]]
                    [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs:77 OnResolved()]]
                    [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs:50 Setup()]]
                }
                class CoinLogic  {
                    [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/state/CoinLogic.cs ScriptFile]]
                    [Methods]
                    [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/state/CoinLogic.cs:12 GetInitialState()]]
                }
                Coin::CoinLogic ---> CoinLogic
            }
            class MapLogic  {
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/map/state/MapLogic.cs ScriptFile]]
                [Methods]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/map/state/MapLogic.cs:12 GetInitialState()]]
            }
            Map::DeathPlane ---> DeathPlane
            Map::Jumpshroom2 ---> Jumpshroom
            Map::Coin ---> Coin
            Map::MapLogic ---> MapLogic
        }
        package InGameUI-Scene [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/in_game_ui/InGameUI.tscn]] {
            class InGameUI  {
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/in_game_ui/InGameUI.cs ScriptFile]]
                [Dependencies]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/in_game_ui/InGameUI.cs:20 AppRepo]] - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/domain/AppRepo.cs Script]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/in_game_ui/InGameUI.cs:21 GameRepo]] - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/domain/GameRepo.cs Script]]
                --
                [Nodes]
                CoinScene - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/in_game_ui/coin_scene/CoinScene.tscn Script]]
                [Properties]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/in_game_ui/InGameUI.cs:27 CoinsLabel]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/in_game_ui/InGameUI.cs:35 InGameUIBinding]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/in_game_ui/InGameUI.cs:33 InGameUILogic]]
                --
                [Interface Methods]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/in_game_ui/InGameUI.cs:59 SetCoinsLabel()]]
                [Methods]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/in_game_ui/InGameUI.cs:16 _Notification()]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/in_game_ui/InGameUI.cs:62 OnExitTree()]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/in_game_ui/InGameUI.cs:41 OnResolved()]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/in_game_ui/InGameUI.cs:39 Setup()]]
            }
            package CoinScene-Scene [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/in_game_ui/coin_scene/CoinScene.tscn]] {
                class CoinScene << (S,black) >> {
                    [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/in_game_ui/coin_scene/CoinScene.tscn SceneFile]]
                    [Nodes]
                    UICoin - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs Script]]
                }
                package Coin-Scene [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.tscn]] {
                    class Coin  {
                        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs ScriptFile]]
                        [Dependencies]
                        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs:34 GameRepo]] - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/domain/GameRepo.cs Script]]
                        --
                        [Interface Properties]
                        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs:36 CoinLogic]] - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/state/CoinLogic.cs Script]]
                        [Properties]
                        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs:21 AnimationPlayer]]
                        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs:39 CoinBinding]]
                        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs:22 CoinModel]]
                        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs:28 CollectionTimeInSeconds]]
                        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs:45 CollectorDetector]]
                        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs:37 Settings]]
                        --
                        [Methods]
                        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs:17 _Notification()]]
                        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs:110 OnCollectorDetectorBodyEntered()]]
                        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs:120 OnExitTree()]]
                        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs:107 OnPhysicsProcess()]]
                        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs:62 OnReady()]]
                        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs:77 OnResolved()]]
                        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/Coin.cs:50 Setup()]]
                    }
                    class CoinLogic  {
                        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/state/CoinLogic.cs ScriptFile]]
                        [Methods]
                        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/coin/state/CoinLogic.cs:12 GetInitialState()]]
                    }
                    Coin::CoinLogic ---> CoinLogic
                }
                CoinScene::UICoin ---> Coin
            }
            InGameUI::CoinScene ---> CoinScene
        }
        package InGameAudio-Scene [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/in_game_audio/InGameAudio.tscn]] {
            class InGameAudio  {
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/in_game_audio/InGameAudio.cs ScriptFile]]
                [Dependencies]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/in_game_audio/InGameAudio.cs:26 AppRepo]] - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/domain/AppRepo.cs Script]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/in_game_audio/InGameAudio.cs:28 GameRepo]] - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/domain/GameRepo.cs Script]]
                --
                [Nodes]
                GameMusic - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/in_game_audio/DimmableAudioStreamPlayer.cs Script]]
                MainMenuMusic - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/in_game_audio/DimmableAudioStreamPlayer.cs Script]]
                [Properties]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/in_game_audio/InGameAudio.cs:16 Bounce]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/in_game_audio/InGameAudio.cs:15 CoinCollected]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/in_game_audio/InGameAudio.cs:20 GameMusic]] - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/in_game_audio/DimmableAudioStreamPlayer.cs Script]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/in_game_audio/InGameAudio.cs:36 InGameAudioBinding]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/in_game_audio/InGameAudio.cs:34 InGameAudioLogic]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/in_game_audio/InGameAudio.cs:19 MainMenuMusic]] - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/in_game_audio/DimmableAudioStreamPlayer.cs Script]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/in_game_audio/InGameAudio.cs:17 PlayerDied]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/in_game_audio/InGameAudio.cs:18 PlayerJumped]]
                --
                [Methods]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/in_game_audio/InGameAudio.cs:11 _Notification()]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/in_game_audio/InGameAudio.cs:71 OnExitTree()]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/in_game_audio/InGameAudio.cs:42 OnResolved()]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/in_game_audio/InGameAudio.cs:40 Setup()]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/in_game_audio/InGameAudio.cs:84 StartGameMusic()]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/in_game_audio/InGameAudio.cs:77 StartMainMenuMusic()]]
            }
            class DimmableAudioStreamPlayer  {
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/in_game_audio/DimmableAudioStreamPlayer.cs ScriptFile]]
                [Properties]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/in_game_audio/DimmableAudioStreamPlayer.cs:23 FadeTween]]
                --
                [Interface Methods]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/in_game_audio/DimmableAudioStreamPlayer.cs:33 FadeIn()]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/in_game_audio/DimmableAudioStreamPlayer.cs:39 FadeOut()]]
                [Methods]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/in_game_audio/DimmableAudioStreamPlayer.cs:27 _Ready()]]
                [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/in_game_audio/DimmableAudioStreamPlayer.cs:45 SetupFade()]]
            }
            InGameAudio::GameMusic ---> DimmableAudioStreamPlayer
        }
        class DeathMenu  {
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/death_menu/DeathMenu.cs ScriptFile]]
            [Properties]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/death_menu/DeathMenu.cs:38 AnimationPlayer]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/death_menu/DeathMenu.cs:39 FadeAnimationPlayer]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/death_menu/DeathMenu.cs:37 MainMenuButton]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/death_menu/DeathMenu.cs:36 TryAgainButton]]
            --
            [Interface Methods]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/death_menu/DeathMenu.cs:57 Animate()]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/death_menu/DeathMenu.cs:60 FadeIn()]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/death_menu/DeathMenu.cs:62 FadeOut()]]
            [Methods]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/death_menu/DeathMenu.cs:23 _Notification()]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/death_menu/DeathMenu.cs:68 OnAnimationFinished()]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/death_menu/DeathMenu.cs:50 OnExitTree()]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/death_menu/DeathMenu.cs:66 OnMainMenuPressed()]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/death_menu/DeathMenu.cs:43 OnReady()]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/death_menu/DeathMenu.cs:64 OnTryAgainPressed()]]
        }
        class WinMenu  {
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/win_menu/WinMenu.cs ScriptFile]]
            [Properties]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/win_menu/WinMenu.cs:26 AnimationPlayer]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/win_menu/WinMenu.cs:25 MainMenuButton]]
            --
            [Interface Methods]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/win_menu/WinMenu.cs:46 FadeIn()]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/win_menu/WinMenu.cs:51 FadeOut()]]
            [Methods]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/win_menu/WinMenu.cs:21 _Notification()]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/win_menu/WinMenu.cs:48 OnAnimationFinished()]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/win_menu/WinMenu.cs:42 OnExitTree()]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/win_menu/WinMenu.cs:44 OnMainMenuPressed()]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/win_menu/WinMenu.cs:40 OnReady()]]
        }
        class PauseMenu  {
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/pause_menu/PauseMenu.cs ScriptFile]]
            [Properties]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/pause_menu/PauseMenu.cs:32 AnimationPlayer]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/pause_menu/PauseMenu.cs:31 MainMenuButton]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/pause_menu/PauseMenu.cs:29 ResumeButton]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/pause_menu/PauseMenu.cs:30 SaveButton]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/pause_menu/PauseMenu.cs:34 SaveOverlay]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/pause_menu/PauseMenu.cs:33 SaveOverlayAnimationPlayer]]
            --
            [Interface Methods]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/pause_menu/PauseMenu.cs:74 FadeIn()]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/pause_menu/PauseMenu.cs:79 FadeOut()]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/pause_menu/PauseMenu.cs:82 OnSaveCompleted()]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/pause_menu/PauseMenu.cs:81 OnSaveStarted()]]
            [Methods]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/pause_menu/PauseMenu.cs:25 _Notification()]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/pause_menu/PauseMenu.cs:85 Animate()]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/pause_menu/PauseMenu.cs:76 OnAnimationFinished()]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/pause_menu/PauseMenu.cs:62 OnExitTree()]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/pause_menu/PauseMenu.cs:70 OnMainMenuPressed()]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/pause_menu/PauseMenu.cs:54 OnReady()]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/pause_menu/PauseMenu.cs:71 OnResumePressed()]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/pause_menu/PauseMenu.cs:72 OnSavePressed()]]
        }
        class GameLogic  {
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/state/GameLogic.cs ScriptFile]]
            [Methods]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/state/GameLogic.cs:16 GetInitialState()]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/state/GameLogic.cs:18 OnStart()]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/state/GameLogic.cs:27 OnStop()]]
        }
        class GameRepo  {
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/domain/GameRepo.cs ScriptFile]]
            [Constructors]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/domain/GameRepo.cs:124 GameRepo]]()
            [Interface Properties]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/domain/GameRepo.cs:106 CameraBasis]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/domain/GameRepo.cs:109 GlobalCameraDirection]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/domain/GameRepo.cs:99 IsMouseCaptured]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/domain/GameRepo.cs:101 IsPaused]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/domain/GameRepo.cs:113 NumCoinsAtStart]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/domain/GameRepo.cs:111 NumCoinsCollected]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/domain/GameRepo.cs:103 PlayerGlobalPosition]]
            --
            [Interface Methods]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/domain/GameRepo.cs:167 OnFinishCoinCollection()]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/domain/GameRepo.cs:183 OnGameEnded()]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/domain/GameRepo.cs:181 OnJump()]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/domain/GameRepo.cs:202 OnJumpshroomUsed()]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/domain/GameRepo.cs:190 Pause()]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/domain/GameRepo.cs:196 Resume()]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/domain/GameRepo.cs:157 SetCameraBasis()]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/domain/GameRepo.cs:154 SetIsMouseCaptured()]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/domain/GameRepo.cs:204 SetNumCoinsAtStart()]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/domain/GameRepo.cs:207 SetNumCoinsCollected()]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/domain/GameRepo.cs:151 SetPlayerGlobalPosition()]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/domain/GameRepo.cs:160 StartCoinCollection()]]
            [Methods]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/domain/GameRepo.cs:212 Dispose()]]
            [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/game/domain/GameRepo.cs:230 Dispose()]]
        }
        Game::PlayerCamera ---> PlayerCamera
        Game::Player ---> Player
        Game::Map ---> Map
        Game::InGameUi ---> InGameUI
        Game::InGameAudio ---> InGameAudio
        Game::DeathMenu ---> DeathMenu
        Game::WinMenu ---> WinMenu
        Game::PauseMenu ---> PauseMenu
        Game::GameLogic ---> GameLogic
        Game::GameRepo ---> GameRepo
    }
    class SettingsMenu  {
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs ScriptFile]]
        [Dependencies]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:26 AppRepo]] - [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/app/domain/AppRepo.cs Script]]
        --
        [Properties]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:31 ApplyButton]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:84 Balanced]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:98 Bilinear]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:171 Bloom]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:173 BloomDisabled]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:175 BloomEnabled]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:35 DisplayMode]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:42 ExclusiveFullscreen]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:33 ExitButton]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:69 FPS120]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:71 FPS144]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:59 FPS30]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:61 FPS40]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:63 FPS60]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:65 FPS72]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:67 FPS90]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:73 FPSUnlimited]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:100 FSR1]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:104 FSR2]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:40 Fullscreen]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:128 FXAA]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:149 GIQualityDisabled]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:153 GIQualityHigh]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:151 GIQualityLow]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:147 GlobalIlluminationQuality]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:139 GlobalIlluminationType]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:141 LightmapGI]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:57 MaxFPS]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:102 MetalFXSpatial]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:106 MetalFXTemporal]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:114 MSAA]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:118 Msaa2X]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:120 Msaa4X]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:122 Msaa8X]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:116 MsaaDisabled]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:93 Native]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:81 Performance]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:87 Quality]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:75 ResolutionScale]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:96 ResolutionScaleFilter]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:145 SDFGI]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:132 ShadowMapping]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:135 ShadowsDisabled]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:137 ShadowsEnabled]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:130 SMAA]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:124 SSAA]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:126 SSAADisabled]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:155 SSAO]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:157 SSAODisabled]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:161 SSAOHigh]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:159 SSAOMedium]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:163 SSIL]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:165 SSILDisabled]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:169 SSILHigh]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:167 SSILMedium]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:108 TAA]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:110 TaaDisabled]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:112 TaaEnabled]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:78 UltraPerformance]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:90 UltraQuality]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:177 VolumetricFog]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:179 VolumetricFogDisabled]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:181 VolumetricFogEnabled]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:143 VoxelGI]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:44 VSync]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:53 VSyncAdaptive]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:47 VSyncDisabled]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:50 VSyncEnabled]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:55 VSyncMailbox]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:38 Windowed]]
        --
        [Interface Methods]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:217 LoadDefaultSettings()]]
        [Methods]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:21 _Notification()]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:492 MakeButtonGroup()]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:450 OnApplyButtonPressed()]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:490 OnExitButtonPressed()]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:444 OnExitTree()]]
        [[vscode://file/f:/BHamAndEggs/Repo/GameDemo/src/menus/settings_menu/SettingsMenu.cs:194 OnReady()]]
    }
    App::Menu ---> Menu
    App::Splash ---> Splash
    App::AppLogic ---> AppLogic
    App::AppRepo ---> AppRepo
    App::Game ---> Game
    App::SettingsMenu ---> SettingsMenu
}

@enduml